[package]
name = "jack_compiler"
version = "0.1.0"
authors = ["tiagodeliberali <tiago.santos@quintoandar.com.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"